apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: test-argocd-01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: external-nfs-sc
