apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: test-app
  name: test-app
  namespace: test-argocd-01
spec:
  host: "test-app-01.apps.cluster-sd92l.sandbox259.opentlc.com"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: test-app
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted
