apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
  namespace: test-argocd-03
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp3-csi
